### ISSUE TITLE
Тесты пакета DataStructurePackage

### ISSUE THREAD

**Issue by aksilont** [EncodedTeam/MdEditor#7]
Строка 50 и 60 в QueueTests повторяются сообщения ошибки

DoublyLinkedList строка 29:
`private(set) var head: Node<T>? `
может все-таки оставить приватными 
`private var head: Node<T>?`
зачем они нам извне?

Для тестов можно просто использовать pop и removeLast

Тоже самое и с tail

**Comment by efimovmay** [comment]
про повтор ошибки, не считаю критичным. если тест не пройдет, будет понятно к чему это относится 

про head и tail согласен
