### ISSUE TITLE
Вопрос реструктуризации репозитория

### ISSUE THREAD

**Issue by aksilont** [EncodedTeam/MdEditor#8]
Предложение создать папку App и туда закинуть наше приложение, а пакеты оставить за областью приложения
![telegram-cloud-photo-size-2-5246774964563071675-y](https://github.com/EncodedTeam/MdEditor/assets/64919648/0843db8f-f7c9-4a34-ac3e-55ee3fccfc96)
Репозиторий будет выглядеть так:
![telegram-cloud-photo-size-2-5246774964563071681-y](https://github.com/EncodedTeam/MdEditor/assets/64919648/b2e637ce-f555-4479-9d57-f8ef0be5f589)

Приложение будет разделено между пакетами и пакетами

**Comment by dutysniper** [comment]
Поддерживаю

**Comment by efimovmay** [comment]
Думаю тогда название папки не App должно быть, а MdEditor

**Comment by efimovmay** [comment]
У Кирилла еще тесты не в папке приложения а отдельно
<img width="187" alt="Снимок экрана 2024-01-08 в 19 35 03" src="https://github.com/EncodedTeam/MdEditor/assets/118847548/69ac0780-8dcf-48b1-9347-ae5f85a71a80">

**Comment by aksilont** [comment]
> Думаю тогда название папки не App должно быть, а MdEditor

Если мы назовем папку MdEditor вместо App, тогда путь к проекту у нас будет такой:
~/MdEditor/MdEditor/MdEditor.xcodeproj

**Comment by dutysniper** [comment]
Предлагаю папку сделать App, исключив дублирование
